pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                dir('lesson_31') {
                    bat 'python -m venv .venv'
                    bat '.venv\\Scripts\\pip install -r requirements.txt'
                }
            }
        }

        stage('Run tests') {
            steps {
                dir('lesson_31') {
                    bat '.venv\\Scripts\\pytest -q --alluredir=allure-results tests'
                }
            }
        }

        stage('Publish results') {
            steps {
                dir('lesson_31') {
                    allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
                }
            }
        }
    }
}
